// <auto-generated />
namespace CA_sem2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class moreseeding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moreseeding));
        
        string IMigrationMetadata.Id
        {
            get { return "201403061300523_more seeding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
