// <auto-generated />
namespace CA_sem2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class uuu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uuu));
        
        string IMigrationMetadata.Id
        {
            get { return "201403141604114_uuu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
